#!/usr/bin/env python3
"""Emit icon_textures_data.h — the QuickAccess icon PNGs as C byte arrays.

Cursor Finder loads these via Textures_GetOrCreateFromMemory (the same path its
preset masks already use — no Windows resource lookup, no module handle). This
sidesteps the FindResource "resource not found" failure the .rc/RCDATA path
hits in this Nexus/CrossOver build. The icon PNGs are rasterized from the
Cursor Finder icon SVGs (normal + hover) at 128x128 via a browser canvas.
Regenerate after re-rasterizing the icon PNGs:

    python3 gen_icon_data.py    # run from the assets/ folder
"""
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
TEX = HERE / "textures"
OUT = HERE / "icon_textures_data.h"

# (C symbol, filename) — names must match the kIcon* usage in entry.cpp.
ICONS = [
    ("kIconCursor",      "icon-cursor.png"),
    ("kIconCursorHover", "icon-cursor-hover.png"),
]


def emit_array(sym: str, data: bytes) -> str:
    body = []
    for i in range(0, len(data), 20):
        body.append("    " + ",".join(str(b) for b in data[i:i + 20]) + ",")
    return (f"inline const unsigned char {sym}[] = {{\n"
            + "\n".join(body)
            + f"\n}};\ninline const unsigned int {sym}_len = {len(data)}u;\n")


def main() -> None:
    parts = [
        "// GENERATED by gen_icon_data.py — do not edit by hand.",
        "// The QuickAccess icon PNGs (normal + brightened hover), embedded as byte",
        "// arrays and loaded via Textures_GetOrCreateFromMemory (see cursor/src/entry.cpp).",
        "#pragma once",
        "",
        "namespace cursor_art {",
        "",
    ]
    for sym, fname in ICONS:
        data = (TEX / fname).read_bytes()
        parts.append(f"// {fname} ({len(data)} bytes)")
        parts.append(emit_array(sym, data))
    parts.append("} // namespace cursor_art")
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
